-- M1固定DDL快照；历史迁移不引用未来ORM字段。

CREATE TABLE borough (
	borough_id SMALLSERIAL NOT NULL, 
	borough_name VARCHAR(40) NOT NULL, 
	display_name VARCHAR(80), 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	PRIMARY KEY (borough_id), 
	CONSTRAINT ck_borough_id CHECK (borough_id BETWEEN 1 AND 5), 
	UNIQUE (borough_name)
);

CREATE TABLE contributing_factor (
	factor_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	canonical_name TEXT NOT NULL, 
	display_name TEXT, 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	PRIMARY KEY (factor_id), 
	CONSTRAINT ck_factor_name CHECK (btrim(canonical_name) <> ''), 
	UNIQUE (canonical_name)
);

CREATE TABLE dataset_state (
	state_id SMALLSERIAL NOT NULL, 
	revision BIGINT DEFAULT 0 NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	last_change_note TEXT NOT NULL, 
	PRIMARY KEY (state_id), 
	CONSTRAINT ck_dataset_singleton CHECK (state_id = 1 AND revision >= 0)
);

CREATE TABLE role (
	role_id SMALLSERIAL NOT NULL, 
	role_code VARCHAR(20) NOT NULL, 
	role_name VARCHAR(60) NOT NULL, 
	PRIMARY KEY (role_id), 
	CONSTRAINT ck_role_fixed CHECK ((role_id = 1 AND role_code = 'ADMIN') OR (role_id = 2 AND role_code = 'MANAGER') OR (role_id = 3 AND role_code = 'VIEWER')), 
	UNIQUE (role_code)
);

CREATE TABLE vehicle_type (
	vehicle_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	canonical_name TEXT NOT NULL, 
	display_name TEXT, 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	PRIMARY KEY (vehicle_type_id), 
	CONSTRAINT ck_vehicle_type_name CHECK (btrim(canonical_name) <> ''), 
	UNIQUE (canonical_name)
);

CREATE TABLE app_user (
	user_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	username VARCHAR(80) NOT NULL, 
	password_hash TEXT NOT NULL, 
	display_name VARCHAR(80) NOT NULL, 
	role_id SMALLINT NOT NULL, 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	auth_version INTEGER DEFAULT 1 NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	version INTEGER DEFAULT 1 NOT NULL, 
	PRIMARY KEY (user_id), 
	CONSTRAINT ck_user_versions CHECK (auth_version > 0 AND version > 0), 
	CONSTRAINT ck_user_names CHECK (btrim(username) <> '' AND btrim(display_name) <> ''), 
	FOREIGN KEY(role_id) REFERENCES role (role_id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_app_user_username_lower ON app_user (lower(username));

CREATE TABLE location (
	location_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	location_key TEXT NOT NULL, 
	key_input JSONB DEFAULT '{}'::jsonb NOT NULL, 
	borough_id SMALLINT, 
	zip_code VARCHAR(20), 
	on_street_name TEXT, 
	cross_street_name TEXT, 
	off_street_name TEXT, 
	geom geometry(POINT,4326), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (location_id), 
	CONSTRAINT ck_location_coordinates CHECK (geom IS NULL OR (NOT ST_IsEmpty(geom) AND ST_X(geom) BETWEEN -180 AND 180 AND ST_Y(geom) BETWEEN -90 AND 90)), 
	CONSTRAINT ck_location_key_input CHECK (jsonb_typeof(key_input) = 'object'), 
	UNIQUE (location_key), 
	FOREIGN KEY(borough_id) REFERENCES borough (borough_id) ON DELETE RESTRICT
);

CREATE INDEX ix_location_borough ON location (borough_id, location_id);

CREATE INDEX ix_location_geography ON location USING gist ((geom::geography)) WHERE geom IS NOT NULL;

CREATE INDEX ix_location_geom ON location USING gist (geom) WHERE geom IS NOT NULL;

CREATE TABLE audit_log (
	audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	actor_id BIGINT, 
	action VARCHAR(60) NOT NULL, 
	entity_type VARCHAR(50) NOT NULL, 
	entity_id TEXT, 
	request_id UUID, 
	details JSONB DEFAULT '{}'::jsonb NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (audit_id), 
	FOREIGN KEY(actor_id) REFERENCES app_user (user_id) ON DELETE RESTRICT
);

CREATE TABLE import_batch (
	batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	request_id UUID NOT NULL, 
	request_hash VARCHAR(64) NOT NULL, 
	manifest_hash VARCHAR(64) NOT NULL, 
	cleaning_version VARCHAR(40) NOT NULL, 
	input_manifest JSONB DEFAULT '{}'::jsonb NOT NULL, 
	requested_start DATE, 
	requested_end DATE, 
	status VARCHAR(30) NOT NULL, 
	rows_read BIGINT DEFAULT 0 NOT NULL, 
	rows_accepted BIGINT DEFAULT 0 NOT NULL, 
	rows_rejected BIGINT DEFAULT 0 NOT NULL, 
	rows_skipped BIGINT DEFAULT 0 NOT NULL, 
	created_by BIGINT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	published_revision BIGINT, 
	worker_token UUID, 
	lease_expires_at TIMESTAMP WITH TIME ZONE, 
	attempt_no INTEGER DEFAULT 0 NOT NULL, 
	error_summary TEXT, 
	PRIMARY KEY (batch_id), 
	CONSTRAINT ck_import_status CHECK (status IN ('UPLOADED', 'VALIDATING', 'READY', 'PUBLISHING', 'SUCCEEDED', 'FAILED', 'CANCELLED')), 
	CONSTRAINT ck_import_counts CHECK (rows_read >= 0 AND rows_accepted >= 0 AND rows_rejected >= 0 AND rows_skipped >= 0 AND attempt_no >= 0), 
	CONSTRAINT ck_import_period CHECK ((requested_start IS NULL AND requested_end IS NULL) OR (requested_start IS NOT NULL AND requested_end IS NOT NULL AND requested_start < requested_end)), 
	CONSTRAINT ck_import_balance CHECK (status NOT IN ('READY', 'PUBLISHING', 'SUCCEEDED') OR rows_read = rows_accepted + rows_rejected + rows_skipped), 
	CONSTRAINT ck_import_published CHECK (status <> 'SUCCEEDED' OR (published_revision IS NOT NULL AND published_revision > 0 AND finished_at IS NOT NULL)), 
	CONSTRAINT ck_import_request_hash CHECK (request_hash ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_import_manifest_hash CHECK (manifest_hash ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_import_manifest_object CHECK (jsonb_typeof(input_manifest) = 'object'), 
	UNIQUE (request_id), 
	FOREIGN KEY(created_by) REFERENCES app_user (user_id) ON DELETE RESTRICT
);

CREATE TABLE intersection (
	intersection_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	intersection_code VARCHAR(40) NOT NULL, 
	borough_id SMALLINT, 
	street_a TEXT NOT NULL, 
	street_b TEXT NOT NULL, 
	center_geom geometry(POINT,4326) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	source_method VARCHAR(30) NOT NULL, 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	supersedes_id BIGINT, 
	confirmation_note TEXT, 
	confirmed_by BIGINT, 
	confirmed_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	version INTEGER DEFAULT 1 NOT NULL, 
	PRIMARY KEY (intersection_id), 
	CONSTRAINT ck_intersection_status CHECK (status IN ('CANDIDATE', 'CONFIRMED', 'REJECTED')), 
	CONSTRAINT ck_intersection_source CHECK (source_method IN ('DERIVED', 'MANUAL', 'EXTERNAL')), 
	CONSTRAINT ck_intersection_fields CHECK (version > 0 AND btrim(street_a) <> '' AND btrim(street_b) <> ''), 
	CONSTRAINT ck_intersection_supersedes CHECK (supersedes_id IS NULL OR supersedes_id <> intersection_id), 
	CONSTRAINT ck_intersection_confirmation CHECK (status <> 'CONFIRMED' OR (confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL AND confirmation_note IS NOT NULL AND btrim(confirmation_note) <> '')), 
	CONSTRAINT ck_intersection_coordinates CHECK (NOT ST_IsEmpty(center_geom) AND ST_X(center_geom) BETWEEN -180 AND 180 AND ST_Y(center_geom) BETWEEN -90 AND 90), 
	UNIQUE (intersection_code), 
	FOREIGN KEY(borough_id) REFERENCES borough (borough_id) ON DELETE RESTRICT, 
	FOREIGN KEY(supersedes_id) REFERENCES intersection (intersection_id) ON DELETE RESTRICT, 
	FOREIGN KEY(confirmed_by) REFERENCES app_user (user_id) ON DELETE RESTRICT
);

CREATE INDEX ix_intersection_center ON intersection USING gist (center_geom);

CREATE TABLE risk_rule (
	rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	rule_code VARCHAR(40) NOT NULL, 
	version_no INTEGER NOT NULL, 
	rule_name TEXT NOT NULL, 
	weight_collision NUMERIC(10, 2) NOT NULL, 
	weight_injured NUMERIC(10, 2) NOT NULL, 
	weight_killed NUMERIC(10, 2) NOT NULL, 
	weight_vru NUMERIC(10, 2) NOT NULL, 
	threshold_medium NUMERIC(12, 2) NOT NULL, 
	threshold_high NUMERIC(12, 2) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	rationale TEXT NOT NULL, 
	created_by BIGINT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (rule_id), 
	CONSTRAINT uq_rule_version UNIQUE (rule_code, version_no), 
	CONSTRAINT ck_rule_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'RETIRED')), 
	CONSTRAINT ck_rule_values CHECK (version_no > 0 AND weight_collision >= 0 AND weight_injured >= 0 AND weight_killed >= 0 AND weight_vru >= 0 AND threshold_medium >= 0 AND threshold_high > threshold_medium AND weight_collision <> 'NaN'::numeric AND weight_injured <> 'NaN'::numeric AND weight_killed <> 'NaN'::numeric AND weight_vru <> 'NaN'::numeric AND threshold_medium <> 'NaN'::numeric AND threshold_high <> 'NaN'::numeric), 
	FOREIGN KEY(created_by) REFERENCES app_user (user_id) ON DELETE RESTRICT
);

CREATE TABLE location_assignment (
	location_id BIGINT NOT NULL, 
	intersection_id BIGINT, 
	match_status VARCHAR(30) NOT NULL, 
	match_method VARCHAR(40) NOT NULL, 
	algorithm_version VARCHAR(40) NOT NULL, 
	distance_m NUMERIC(10, 2), 
	evidence JSONB DEFAULT '{}'::jsonb NOT NULL, 
	reviewed_by BIGINT, 
	reviewed_at TIMESTAMP WITH TIME ZONE, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	version INTEGER DEFAULT 1 NOT NULL, 
	PRIMARY KEY (location_id), 
	CONSTRAINT ck_assignment_status CHECK (match_status IN ('UNMATCHED', 'CANDIDATE', 'AUTO_MATCHED', 'MANUAL_CONFIRMED', 'REJECTED')), 
	CONSTRAINT ck_assignment_target CHECK (match_status NOT IN ('AUTO_MATCHED', 'MANUAL_CONFIRMED') OR intersection_id IS NOT NULL), 
	CONSTRAINT ck_assignment_review CHECK (match_status <> 'MANUAL_CONFIRMED' OR (reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)), 
	CONSTRAINT ck_assignment_distance CHECK (distance_m >= 0 AND distance_m <> 'NaN'::numeric), 
	CONSTRAINT ck_assignment_version CHECK (version > 0), 
	FOREIGN KEY(location_id) REFERENCES location (location_id) ON DELETE RESTRICT, 
	FOREIGN KEY(intersection_id) REFERENCES intersection (intersection_id) ON DELETE RESTRICT, 
	FOREIGN KEY(reviewed_by) REFERENCES app_user (user_id) ON DELETE RESTRICT
);

CREATE INDEX ix_assignment_intersection ON location_assignment (intersection_id, location_id);

CREATE TABLE raw_record (
	raw_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	batch_id BIGINT NOT NULL, 
	source_kind VARCHAR(12) NOT NULL, 
	row_no BIGINT NOT NULL, 
	source_key TEXT, 
	payload JSONB DEFAULT '{}'::jsonb NOT NULL, 
	row_hash VARCHAR(64) NOT NULL, 
	validation_status VARCHAR(20) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (raw_record_id), 
	CONSTRAINT uq_raw_batch_line UNIQUE (batch_id, source_kind, row_no), 
	CONSTRAINT ck_raw_source CHECK (source_kind IN ('CRASHES', 'PERSON', 'VEHICLES')), 
	CONSTRAINT ck_raw_validation CHECK (validation_status IN ('UNVALIDATED', 'ACCEPTED', 'REJECTED', 'SKIPPED')), 
	CONSTRAINT ck_raw_line CHECK (row_no > 0), 
	CONSTRAINT ck_raw_hash CHECK (row_hash ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_raw_payload CHECK (jsonb_typeof(payload) = 'object'), 
	FOREIGN KEY(batch_id) REFERENCES import_batch (batch_id) ON DELETE RESTRICT
);

CREATE INDEX ix_raw_batch_source_key ON raw_record (batch_id, source_kind, source_key);

CREATE TABLE risk_run (
	run_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	request_id UUID NOT NULL, 
	request_hash VARCHAR(64) NOT NULL, 
	rule_id BIGINT NOT NULL, 
	period_start DATE NOT NULL, 
	period_end DATE NOT NULL, 
	input_revision BIGINT, 
	status VARCHAR(20) NOT NULL, 
	input_manifest JSONB DEFAULT '{}'::jsonb NOT NULL, 
	coverage_summary JSONB DEFAULT '{}'::jsonb NOT NULL, 
	requested_by BIGINT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	worker_token UUID, 
	lease_expires_at TIMESTAMP WITH TIME ZONE, 
	attempt_no INTEGER DEFAULT 0 NOT NULL, 
	error_summary TEXT, 
	PRIMARY KEY (run_id), 
	CONSTRAINT ck_run_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')), 
	CONSTRAINT ck_run_period CHECK (period_start < period_end), 
	CONSTRAINT ck_run_counts CHECK (attempt_no >= 0 AND (input_revision IS NULL OR input_revision >= 0)), 
	CONSTRAINT ck_run_complete CHECK (status <> 'SUCCEEDED' OR (input_revision IS NOT NULL AND finished_at IS NOT NULL)), 
	CONSTRAINT ck_run_request_hash CHECK (request_hash ~ '^[0-9a-f]{64}$'), 
	UNIQUE (request_id), 
	FOREIGN KEY(rule_id) REFERENCES risk_rule (rule_id) ON DELETE RESTRICT, 
	FOREIGN KEY(requested_by) REFERENCES app_user (user_id) ON DELETE RESTRICT
);

CREATE TABLE collision (
	collision_id BIGSERIAL NOT NULL, 
	location_id BIGINT NOT NULL, 
	crash_date DATE NOT NULL, 
	crash_time TIME WITHOUT TIME ZONE, 
	source_record_id BIGINT NOT NULL, 
	imported_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (collision_id), 
	CONSTRAINT ck_collision_source_id CHECK (collision_id > 0), 
	FOREIGN KEY(location_id) REFERENCES location (location_id) ON DELETE RESTRICT, 
	UNIQUE (source_record_id), 
	FOREIGN KEY(source_record_id) REFERENCES raw_record (raw_record_id) ON DELETE RESTRICT
);

CREATE INDEX ix_collision_date_id ON collision (crash_date DESC, collision_id DESC);

CREATE INDEX ix_collision_location_date ON collision (location_id, crash_date);

CREATE TABLE data_issue (
	issue_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	batch_id BIGINT NOT NULL, 
	raw_record_id BIGINT, 
	issue_code VARCHAR(50) NOT NULL, 
	severity VARCHAR(10) NOT NULL, 
	field_name TEXT, 
	description TEXT NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	resolution_note TEXT, 
	resolved_by BIGINT, 
	resolved_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (issue_id), 
	CONSTRAINT ck_issue_severity CHECK (severity IN ('INFO', 'WARNING', 'ERROR')), 
	CONSTRAINT ck_issue_status CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED')), 
	CONSTRAINT ck_issue_resolution CHECK (status <> 'RESOLVED' OR (resolved_by IS NOT NULL AND resolved_at IS NOT NULL AND resolution_note IS NOT NULL AND btrim(resolution_note) <> '')), 
	FOREIGN KEY(batch_id) REFERENCES import_batch (batch_id) ON DELETE RESTRICT, 
	FOREIGN KEY(raw_record_id) REFERENCES raw_record (raw_record_id) ON DELETE RESTRICT, 
	FOREIGN KEY(resolved_by) REFERENCES app_user (user_id) ON DELETE RESTRICT
);

CREATE INDEX ix_issue_batch_status ON data_issue (batch_id, status);

CREATE TABLE risk_profile (
	profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	run_id BIGINT NOT NULL, 
	intersection_id BIGINT NOT NULL, 
	collision_count BIGINT NOT NULL, 
	injured_count BIGINT NOT NULL, 
	killed_count BIGINT NOT NULL, 
	vulnerable_road_user_count BIGINT NOT NULL, 
	incomplete_casualty_collision_count BIGINT NOT NULL, 
	PRIMARY KEY (profile_id), 
	CONSTRAINT uq_profile_run_intersection UNIQUE (run_id, intersection_id), 
	CONSTRAINT ck_profile_counts CHECK (collision_count > 0 AND injured_count >= 0 AND killed_count >= 0 AND vulnerable_road_user_count >= 0 AND incomplete_casualty_collision_count BETWEEN 0 AND collision_count), 
	FOREIGN KEY(run_id) REFERENCES risk_run (run_id) ON DELETE RESTRICT, 
	FOREIGN KEY(intersection_id) REFERENCES intersection (intersection_id) ON DELETE RESTRICT
);

CREATE INDEX ix_profile_intersection_run ON risk_profile (intersection_id, run_id DESC);

CREATE TABLE casualty_stat (
	collision_id BIGINT NOT NULL, 
	persons_injured INTEGER, 
	persons_killed INTEGER, 
	pedestrians_injured INTEGER, 
	pedestrians_killed INTEGER, 
	cyclists_injured INTEGER, 
	cyclists_killed INTEGER, 
	motorists_injured INTEGER, 
	motorists_killed INTEGER, 
	PRIMARY KEY (collision_id), 
	CONSTRAINT ck_casualty_persons_injured CHECK (persons_injured >= 0), 
	CONSTRAINT ck_casualty_persons_killed CHECK (persons_killed >= 0), 
	CONSTRAINT ck_casualty_pedestrians_injured CHECK (pedestrians_injured >= 0), 
	CONSTRAINT ck_casualty_pedestrians_killed CHECK (pedestrians_killed >= 0), 
	CONSTRAINT ck_casualty_cyclists_injured CHECK (cyclists_injured >= 0), 
	CONSTRAINT ck_casualty_cyclists_killed CHECK (cyclists_killed >= 0), 
	CONSTRAINT ck_casualty_motorists_injured CHECK (motorists_injured >= 0), 
	CONSTRAINT ck_casualty_motorists_killed CHECK (motorists_killed >= 0), 
	FOREIGN KEY(collision_id) REFERENCES collision (collision_id) ON DELETE RESTRICT
);

CREATE TABLE collision_factor (
	collision_id BIGINT NOT NULL, 
	factor_order SMALLINT NOT NULL, 
	factor_id BIGINT NOT NULL, 
	PRIMARY KEY (collision_id, factor_order), 
	CONSTRAINT ck_factor_order CHECK (factor_order BETWEEN 1 AND 5), 
	FOREIGN KEY(collision_id) REFERENCES collision (collision_id) ON DELETE RESTRICT, 
	FOREIGN KEY(factor_id) REFERENCES contributing_factor (factor_id) ON DELETE RESTRICT
);

CREATE INDEX ix_factor_collision ON collision_factor (factor_id, collision_id);

CREATE TABLE governance_task (
	task_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	task_code VARCHAR(40) NOT NULL, 
	request_id UUID NOT NULL, 
	request_hash VARCHAR(64) NOT NULL, 
	profile_id BIGINT NOT NULL, 
	title VARCHAR(160) NOT NULL, 
	description TEXT NOT NULL, 
	measure_type VARCHAR(40) NOT NULL, 
	priority VARCHAR(20) NOT NULL, 
	status VARCHAR(30) NOT NULL, 
	created_by BIGINT NOT NULL, 
	assignee_id BIGINT, 
	due_date DATE, 
	effective_on DATE, 
	assessment_scope JSONB DEFAULT '{}'::jsonb NOT NULL, 
	is_simulated BOOLEAN DEFAULT true NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	version INTEGER DEFAULT 1 NOT NULL, 
	PRIMARY KEY (task_id), 
	CONSTRAINT ck_task_status CHECK (status IN ('DRAFT', 'OPEN', 'IN_PROGRESS', 'PENDING_REVIEW', 'COMPLETED', 'CANCELLED')), 
	CONSTRAINT ck_task_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')), 
	CONSTRAINT ck_task_measure CHECK (measure_type IN ('MARKING_MAINTENANCE', 'SIGNAL_REVIEW', 'PEDESTRIAN_FACILITY_REVIEW', 'FIELD_SURVEY', 'OTHER')), 
	CONSTRAINT ck_task_fields CHECK (version > 0 AND btrim(title) <> '' AND btrim(description) <> ''), 
	CONSTRAINT ck_task_simulated CHECK (is_simulated), 
	CONSTRAINT ck_task_draft_delete CHECK (deleted_at IS NULL OR status = 'DRAFT'), 
	CONSTRAINT ck_task_request_hash CHECK (request_hash ~ '^[0-9a-f]{64}$'), 
	UNIQUE (task_code), 
	UNIQUE (request_id), 
	FOREIGN KEY(profile_id) REFERENCES risk_profile (profile_id) ON DELETE RESTRICT, 
	FOREIGN KEY(created_by) REFERENCES app_user (user_id) ON DELETE RESTRICT, 
	FOREIGN KEY(assignee_id) REFERENCES app_user (user_id) ON DELETE RESTRICT
);

CREATE INDEX ix_task_assignee_status ON governance_task (assignee_id, status, updated_at DESC) WHERE deleted_at IS NULL;

CREATE INDEX ix_task_profile ON governance_task (profile_id);

CREATE TABLE person (
	person_id BIGSERIAL NOT NULL, 
	collision_id BIGINT NOT NULL, 
	source_person_id TEXT, 
	source_vehicle_id TEXT, 
	person_type TEXT, 
	person_injury TEXT, 
	person_age SMALLINT, 
	person_sex TEXT, 
	source_record_id BIGINT NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (person_id), 
	CONSTRAINT ck_person_source_id CHECK (person_id > 0), 
	CONSTRAINT ck_person_age_quality CHECK (person_age BETWEEN 0 AND 120), 
	FOREIGN KEY(collision_id) REFERENCES collision (collision_id) ON DELETE RESTRICT, 
	UNIQUE (source_record_id), 
	FOREIGN KEY(source_record_id) REFERENCES raw_record (raw_record_id) ON DELETE RESTRICT
);

CREATE INDEX ix_person_collision ON person (collision_id);

CREATE TABLE vehicle (
	vehicle_id BIGSERIAL NOT NULL, 
	collision_id BIGINT NOT NULL, 
	source_vehicle_id TEXT, 
	vehicle_type_id BIGINT, 
	vehicle_year SMALLINT, 
	travel_direction TEXT, 
	pre_crash TEXT, 
	point_of_impact TEXT, 
	vehicle_damage TEXT, 
	source_record_id BIGINT NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (vehicle_id), 
	CONSTRAINT ck_vehicle_source_id CHECK (vehicle_id > 0), 
	CONSTRAINT ck_vehicle_year_quality CHECK (vehicle_year BETWEEN 1886 AND 2100), 
	FOREIGN KEY(collision_id) REFERENCES collision (collision_id) ON DELETE RESTRICT, 
	FOREIGN KEY(vehicle_type_id) REFERENCES vehicle_type (vehicle_type_id) ON DELETE RESTRICT, 
	UNIQUE (source_record_id), 
	FOREIGN KEY(source_record_id) REFERENCES raw_record (raw_record_id) ON DELETE RESTRICT
);

CREATE INDEX ix_vehicle_collision ON vehicle (collision_id);

CREATE INDEX ix_vehicle_type_collision ON vehicle (vehicle_type_id, collision_id);

CREATE TABLE task_history (
	history_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	task_id BIGINT NOT NULL, 
	sequence_no INTEGER NOT NULL, 
	request_id UUID NOT NULL, 
	request_hash VARCHAR(64) NOT NULL, 
	event_type VARCHAR(30) NOT NULL, 
	from_status VARCHAR(30), 
	to_status VARCHAR(30) NOT NULL, 
	actor_id BIGINT NOT NULL, 
	note TEXT NOT NULL, 
	changed_fields JSONB DEFAULT '{}'::jsonb NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (history_id), 
	CONSTRAINT uq_history_sequence UNIQUE (task_id, sequence_no), 
	CONSTRAINT ck_history_event CHECK (event_type IN ('CREATE', 'EDIT', 'PUBLISH', 'ASSIGN', 'START', 'PROGRESS', 'SUBMIT', 'APPROVE', 'REJECT', 'CANCEL', 'DELETE_DRAFT')), 
	CONSTRAINT ck_history_from CHECK (from_status IN ('DRAFT', 'OPEN', 'IN_PROGRESS', 'PENDING_REVIEW', 'COMPLETED', 'CANCELLED')), 
	CONSTRAINT ck_history_to CHECK (to_status IN ('DRAFT', 'OPEN', 'IN_PROGRESS', 'PENDING_REVIEW', 'COMPLETED', 'CANCELLED')), 
	CONSTRAINT ck_history_fields CHECK (sequence_no > 0 AND btrim(note) <> ''), 
	CONSTRAINT ck_history_request_hash CHECK (request_hash ~ '^[0-9a-f]{64}$'), 
	FOREIGN KEY(task_id) REFERENCES governance_task (task_id) ON DELETE RESTRICT, 
	UNIQUE (request_id), 
	FOREIGN KEY(actor_id) REFERENCES app_user (user_id) ON DELETE RESTRICT
);
